name: Generate SourceCred
on: [pull_request]

jobs:
  GenerateSourcecred:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        SOURCECRED_GITHUB_TOKEN=${GITHUB_TOKEN} docker run -i -v sourcecred_data:/data -e SOURCECRED_GITHUB_TOKEN sourcecred/sourcecred load ${GITHUB_REPOSITORY}
        SOURCECRED_GITHUB_TOKEN=${GITHUB_TOKEN} docker run -i -v sourcecred_data:/data sourcecred/sourcecred scores ${GITHUB_REPOSITORY} > scores.json
        SOURCECRED_GITHUB_TOKEN=${GITHUB_TOKEN} docker run -i -e SOURCECRED_GITHUB_TOKEN sourcecred/widgets < scores.json > contributors.svg
